<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TVMATP310440M" name="GRP-SI - WF 14,SI - WF 11,SI - WF 33,SI - WF 17,SI - WF 15" tests="5" failures="1" timestamp="22 Jun 2016 06:56:41 GMT" time="960.79" errors="0">
  <testcase name="SI_WF11_StartFromScratch_NonSysco_Prep_DefaultLocation_DefaultCategory_MA" time="113.909" classname="com.tests.WorkFlow">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.components.pages.SetupInventoryPage.NonSysco_Prompt(SetupInventoryPage.java:903)
	at com.tests.WorkFlow.SI_WF11_StartFromScratch_NonSysco_Prep_DefaultLocation_DefaultCategory_MA(WorkFlow.java:575)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- SI_WF11_StartFromScratch_NonSysco_Prep_DefaultLocation_DefaultCategory_MA -->
  <testcase name="SI_WF14_StartFromScratch_MultipleList_DefaultLocation_CustomCategory_NU" time="287.141" classname="com.tests.WorkFlow"/>
  <testcase name="SI_WF15_StartFromScratch_MultipleList_CustomLocation_DefaultCategory_NU" time="285.727" classname="com.tests.WorkFlow"/>
  <testcase name="SI_WF17_StartFromScratch_MultipleList_DefaultLocation_SkipCategory_MA" time="214.059" classname="com.tests.WorkFlow"/>
  <testcase name="SI_WF33_OG_DefaultLocation_SuggestedCategory_NU" time="49.034" classname="com.tests.WorkFlow"/>
</testsuite> <!-- GRP-SI - WF 14,SI - WF 11,SI - WF 33,SI - WF 17,SI - WF 15 -->
