<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="tvmatp312483m.ad.infosys.com" name="GRP-SI - WF 22,SI - WF 21" tests="2" failures="2" timestamp="5 Jul 2016 10:33:49 GMT" time="28.306" errors="0">
  <testcase name="SI_WF21_CustomList_CustomLoc_Customcategory_FewItems" time="28.227" classname="com.tests.WorkFlow">
    <failure type="java.lang.AssertionError" message="Timeout : Expected element HomUserNamenot available.">
      <![CDATA[java.lang.AssertionError: Timeout : Expected element HomUserNamenot available.
	at org.testng.Assert.fail(Assert.java:94)
	at zRfghY.c.isTargetAvailable(CommandImpl.java:415)
	at zRfghY.c.sendKeys(CommandImpl.java:340)
	at com.components.pages.LoginPage.signIn(LoginPage.java:104)
	at com.tests.WorkFlow.SI_WF21_CustomList_CustomLoc_Customcategory_FewItems(WorkFlow.java:1639)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- SI_WF21_CustomList_CustomLoc_Customcategory_FewItems -->
  <testcase name="SI_WF21_CustomList_CustomLoc_Customcategory_FewItems" time="28.283" classname="com.tests.WorkFlow">
    <failure type="java.lang.RuntimeException" message="Error occured while closing webdriver sessionError communicating with the remote browser. It may have died.
Build info: version: &amp;apos;2.51.0&amp;apos;, revision: &amp;apos;1af067d&amp;apos;, time: &amp;apos;2016-02-05 19:15:17&amp;apos;
System info: host: &amp;apos;tvmatp312483m.ad.infosys.com&amp;apos;, ip: &amp;apos;10.155.162.74&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;10.11.4&amp;apos;, java.version: &amp;apos;1.8.0_40&amp;apos;
Driver info: driver.version: RemoteWebDriver
Capabilities [{app=/Users/naveen_raj04/Desktop/UOM_Files/Builds/june 22/UOMQASQ.ipa, networkConnectionEnabled=false, databaseEnabled=false, deviceName=Jasobanta&amp;apos;s iPad, platform=MAC, showIOSLog=true, desired={app=/Users/naveen_raj04/Desktop/UOM_Files/Builds/june 22/UOMQASQ.ipa, showIOSLog=true, platformVersion=9.1, autoWebview=false, platformName=iOS, udid=629ad7a98d18f441687e45f79fc8e74e63067da4, deviceName=Jasobanta&amp;apos;s iPad}, platformVersion=9.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, autoWebview=false, platformName=iOS, udid=629ad7a98d18f441687e45f79fc8e74e63067da4}]
Session ID: 0530db92-801e-4425-b295-1d66640846c1">
      <![CDATA[java.lang.RuntimeException: Error occured while closing webdriver sessionError communicating with the remote browser. It may have died.
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp312483m.ad.infosys.com', ip: '10.155.162.74', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_40'
Driver info: driver.version: RemoteWebDriver
Capabilities [{app=/Users/naveen_raj04/Desktop/UOM_Files/Builds/june 22/UOMQASQ.ipa, networkConnectionEnabled=false, databaseEnabled=false, deviceName=Jasobanta's iPad, platform=MAC, showIOSLog=true, desired={app=/Users/naveen_raj04/Desktop/UOM_Files/Builds/june 22/UOMQASQ.ipa, showIOSLog=true, platformVersion=9.1, autoWebview=false, platformName=iOS, udid=629ad7a98d18f441687e45f79fc8e74e63067da4, deviceName=Jasobanta's iPad}, platformVersion=9.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, autoWebview=false, platformName=iOS, udid=629ad7a98d18f441687e45f79fc8e74e63067da4}]
Session ID: 0530db92-801e-4425-b295-1d66640846c1
	at zRfghY.s.b(WebDriverFactory.java:48)
	at com.iwaf.framework.testng.TestNGTestListener.closeTestSession(TestNGTestListener.java:458)
	at com.iwaf.framework.testng.TestNGTestListener.onTestFailure(TestNGTestListener.java:291)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1661)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1645)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:703)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp312483m.ad.infosys.com', ip: '10.155.162.74', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_40'
Driver info: driver.version: RemoteWebDriver
Capabilities [{app=/Users/naveen_raj04/Desktop/UOM_Files/Builds/june 22/UOMQASQ.ipa, networkConnectionEnabled=false, databaseEnabled=false, deviceName=Jasobanta's iPad, platform=MAC, showIOSLog=true, desired={app=/Users/naveen_raj04/Desktop/UOM_Files/Builds/june 22/UOMQASQ.ipa, showIOSLog=true, platformVersion=9.1, autoWebview=false, platformName=iOS, udid=629ad7a98d18f441687e45f79fc8e74e63067da4, deviceName=Jasobanta's iPad}, platformVersion=9.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, autoWebview=false, platformName=iOS, udid=629ad7a98d18f441687e45f79fc8e74e63067da4}]
Session ID: 0530db92-801e-4425-b295-1d66640846c1
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:189)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:526)
	at zRfghY.t.c(WebDriverInstanceGenerator.java:131)
	at zRfghY.s.b(WebDriverFactory.java:45)
	... 24 more
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 10.155.162.74:4723 [/10.155.162.74] failed: Connection refused
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp312483m.ad.infosys.com', ip: '10.155.162.74', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_40'
Driver info: driver.version: RemoteWebDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:64)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 29 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 10.155.162.74:4723 [/10.155.162.74] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:52)
	... 30 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 43 more
]]>
    </failure>
  </testcase> <!-- SI_WF21_CustomList_CustomLoc_Customcategory_FewItems -->
</testsuite> <!-- GRP-SI - WF 22,SI - WF 21 -->
