<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="36.937">
  <properties />
            <testcase name="SI_WF19_CustomList_defaultLoc_defaultcategory" time="36.937" classname="com.sysco.test.WorkFlow">
                <failure type="java.io.IOException"
                  message="Destination &apos;\Users\MrDon\Desktop\Lucky&apos; directory cannot be created"
              >
<![CDATA[java.io.IOException: Destination '\Users\MrDon\Desktop\Lucky' directory cannot be created
  org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1085)
  org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
  com.sysco.jsn_framework.JSN_Framework.takeScreenshot(JSN_Framework.java:186)
  com.sysco.pages.LoginPage.signIn(LoginPage.java:105)
  com.sysco.test.WorkFlow.SI_WF19_CustomList_defaultLoc_defaultcategory(WorkFlow.java:444)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
